### ISSUE TITLE
Use Case?

### ISSUE THREAD

**Issue by vilbht** [estrattonbailey/sharable#1]
Hi Eric

Quite intrigued by the library (love that it uses data- parameters). I'm curious what it does exactly? Is there a demo you have? Each page / post link meta data might be different and therefore have a separate image, separate description etc...

**Comment by estrattonbailey** [comment]
Hey @vilav,

Update, I had commented previously with an incorrect link. I confused two of my libraries, lol.

This library basically watches for clicks on those `data-*` links and then builds a share URL using the data available on the page.

With a normal web experience, this works fine. With SPAs, you would need to update the data in the `<head>` OR pass the parameters directly to each link in your templating library.

You can see it in use in production [here](https://www.genexahealth.com/products/sleepology) on the sidebar. Full transparency, I don't really plan to keep this library updated, but it's pretty simple if you or anyone else would like to submit a PR to improve it.
